In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3])
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)


In [3]:
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)

array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)


In [4]:
array3 = np.array([[1, 2, 3]])
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape)

array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


#### 각 array의 차원

In [5]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [6]:
list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [7]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [8]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


#### 데이터 타입 변경

In [9]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [10]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [11]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


#### arange

In [12]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


#### zero

In [13]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


#### ones

In [14]:
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### reshape: 차원 및 크기 변경

In [15]:
array1 = np.arange(10)
print(array1)

print()

array2 = array1.reshape(2, 5)
print(array2)

print()

array3 = array1.reshape(5, 2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape: ', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape: ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array3 shape:  (5, 2)


In [17]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print(array3d.tolist())

print()

# 3차원 ndarray를 2차원 ndarray로 변환

array5 = array3d.reshape(-1, 1)
print(array5.tolist())
print('array5 shape: ', array5.shape)

print()

# 1차원 ndarray를 2차원 ndarray로 변환

array6 = array1.reshape(-1, 1)
print(array6.tolist())
print('array6 shape: ', array6.shape)

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

[[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:  (8, 1)

[[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:  (8, 1)


#### 단일 값 추출

In [18]:
array1 = np.arange(start = 1, stop = 10)
print(array1)

value = array1[2]     # 3번째 인덱스 위치의 데이터값
print(value)
print(type(value))

print(array1[-1], array1[-2])     # 맨 뒤의 값, 맨 뒤에서 두번째 값

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>
9 8


#### 단일 인덱스를 이용한 데이터값 수정

In [19]:
array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


#### 다차원 ndarray에서 단일 값 추출

In [20]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print(array2d)
print(array2d[0, 0])
print(array2d[0, 1])
print(array2d[1, 0])
print(array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


#### 슬라이싱

In [21]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1[0:3]
print('array3: ', array3)
print(type(array3))

array4 = array1[:3]
print('array4: ', array4)

array5 = array1[3:]
print('array5: ', array5)

array6 = array1[:]
print('array6: ', array6)

array3:  [1 2 3]
<class 'numpy.ndarray'>
array4:  [1 2 3]
array5:  [4 5 6 7 8 9]
array6:  [1 2 3 4 5 6 7 8 9]


#### 2차원 ndarray에서의 슬라이싱

In [22]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [23]:
print('array2d[0]: ', array2d[0])
print('array2d[1]: ', array2d[1])
print('array2d[0] shape: ', array2d[0].shape, 'array2d[1] shape: ', array2d[1].shape)

array2d[0]:  [1 2 3]
array2d[1]:  [4 5 6]
array2d[0] shape:  (3,) array2d[1] shape:  (3,)


#### fancy indexing

In [24]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array3: ', array3.tolist())
array4 = array2d[[0, 1], 0:2]
print('array4: ', array4.tolist())
array5 = array2d[[0, 1]]
print('array5: ', array5.tolist())

array3:  [3, 6]
array4:  [[1, 2], [4, 5]]
array5:  [[1, 2, 3], [4, 5, 6]]


#### boolean indexing

In [25]:
array1d = np.arange(start = 1, stop = 10)
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


#### np.sort(): 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
#### ndarray.sort(): 원 행렬 자체를 정렬한 형태로 변환. 반환 값은 None

In [26]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬: ', org_array)

sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬: ', org_array)

sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array)

# 내림차순 정렬

sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순 정렬: ', sort_array1_desc)

원본 행렬:  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]
내림차순 정렬:  [9 5 3 1]


In [27]:
# 행렬이 2차원 이상일 경우 정렬

array2d = np.array([[8, 12],
                   [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)     # 행 방향 정렬
print('행 방향 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)     # 열 방향 정렬
print('열 방향 정렬:\n', sort_array2d_axis1)

행 방향 정렬:
 [[ 7  1]
 [ 8 12]]
열 방향 정렬:
 [[ 8 12]
 [ 1  7]]


#### np.argsort(): 정렬된 행렬의 원본 행렬 인덱스 반환

In [28]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

# 내림차순 정렬 시
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스: ', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스:  [2 3 0 1]


In [29]:
name_array = np.array(['john', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스: ', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력: ', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스:  [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력:  ['john' 'sarah' 'samuel' 'mike' 'kate']


#### np.dot(): 행렬 내적(행렬 곱)

In [30]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])
b = np.array([[7, 8],
             [9, 10],
             [11, 12]])
dot_product = np.dot(a, b)
print(dot_product)

[[ 58  64]
 [139 154]]


#### np.transpose: 전치 행렬(원 행렬에서 행과 열 위치를 교환한 원소로 구성된 행렬)

In [31]:
a = np.array([[1, 2],
             [3, 4]])
transpose_mat = np.transpose(a)
print(transpose_mat)

[[1 3]
 [2 4]]


In [32]:
import pandas as pd

#### 넘파이 ndarray, 리스트, 딕셔너리를 dataframe으로 변환하기

In [40]:
# 1차원 형태의 데이터를 기반으로 dataframe 생성

col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape: ', array1.shape)

# 리스트를 이용해 dataframe 생성

df_list1 = pd.DataFrame(list1, columns = col_name1)
print('1차원 리스트로 만든 dataframe:\n', df_list1)

# 넘파이 ndarray를 이용해 dataframe 생성

df_array1 = pd.DataFrame(array1, columns = col_name1)
print('1차원 ndarray로 만든 dataframe: \n', df_array1)

array1 shape:  (3,)
1차원 리스트로 만든 dataframe:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 dataframe: 
    col1
0     1
1     2
2     3


In [41]:
# 2차원 형태의 데이터를 기반으로 dataframe 생성

col_name2 = ['col1', 'col2', 'col3']

list2 = [[1, 2, 3],
        [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape: ', array2.shape)

df_list2 = pd.DataFrame(list2, columns = col_name2)
print('2차원 리스트로 만든 dataframe: \n', df_list2)

df_array2 = pd.DataFrame(array2, columns = col_name2)
print('2차원 ndarray로 만든 dataframe: \n', df_array2)

array2 shape:  (2, 3)
2차원 리스트로 만든 dataframe: 
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 dataframe: 
    col1  col2  col3
0     1     2     3
1    11    12    13


In [42]:
# 딕셔너리를 dataframe으로
## 딕셔너리의 키 = 칼럼명, 값 = 키에 해당하는 칼럼 데이터

dict = {'col1' : [1, 11], 'col2' : [2, 22], 'col3' : [3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 dataframe:\n', df_dict)

딕셔너리로 만든 dataframe:
    col1  col2  col3
0     1     2     3
1    11    22    33


#### dataframe을 넘파이 ndarray, 리스트, 딕셔너리로 변환

- values를 이용

In [45]:
# dataframe을 ndarray로 변환

array3 = df_dict.values
print('df_dict.values 타입: ', type(array3), 'df_dict.values shape: ', array3.shape)
print(array3)

print()

# dataframe을 리스트로 변환

list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입: ', type(list3))
print(list3)

print()

# dataframe을 딕셔너리로 변환

dict3 = df_dict.to_dict('list')     # 인자로 list를 넣으면 딕셔너리의 값이 리스트형으로 반환됨
print('df_dict.to_dict() 타입: ', type(dict3))
print(dict3)

df_dict.values 타입:  <class 'numpy.ndarray'> df_dict.values shape:  (2, 3)
[[ 1  2  3]
 [11 22 33]]

df_dict.values.tolist() 타입:  <class 'list'>
[[1, 2, 3], [11, 22, 33]]

df_dict.to_dict() 타입:  <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


#### lambda

In [1]:
lambda_square = lambda x: x**2

print(lambda_square(3))

9


In [3]:
# lambda 식을 이용할 때 여러 개의 값을 입력 인자로 사용해야 할 경우에는 map()함수 사용

a = [1, 2, 3]
squares = map(lambda x: x**2, a)
list(squares)

[1, 4, 9]